apiVersion: apps/v1
kind: Deployment

metadata:
  name: gateway
  namespace: ecommerce

spec:
  replicas: 1

  selector:
    matchLabels:
      app: gateway

  template:
    metadata:
      labels:
        app: gateway

    spec:
      containers:
        - name: gateway

          image: asia-south1-docker.pkg.dev/project-e4b58c33-b31e-44d9-a36/ecommerce-microservices/gateway:latest

          imagePullPolicy: Always

          ports:
            - containerPort: 8006

          env:
            - name: SPRING_PROFILES_ACTIVE
              value: kube


            - name: SPRING_ZIPKIN_BASE_URL
              value: http://zipkin:9411

          resources:
            requests:
              cpu: "100m"
              memory: "256Mi"

            limits:
              cpu: "500m"
              memory: "512Mi"
