apiVersion: v1
kind: Service
metadata:
  name: gateway
  namespace: ecommerce
  annotations:
    cloud.google.com/backend-config: '{"default":"gateway-backend-config"}'
spec:
  selector:
    app: gateway
  ports:
    - port: 80
      targetPort: 8006
  type: ClusterIP
