apiVersion: apps/v1
kind: Deployment

metadata:
  name: product
  namespace: ecommerce

spec:
  replicas: 1

  selector:
    matchLabels:
      app: product

  template:
    metadata:
      labels:
        app: product

    spec:
      containers:
        - name: product

          image: asia-south1-docker.pkg.dev/project-e4b58c33-b31e-44d9-a36/ecommerce-microservices/product:latest

          imagePullPolicy: Always

          ports:
            - containerPort: 8002

          env:
            - name: SPRING_PROFILES_ACTIVE
              value: kube

            - name: SPRING_DATASOURCE_URL
              value: jdbc:postgresql://postgres:5432/product

            - name: SPRING_DATASOURCE_USERNAME
              value: postgres

            - name: SPRING_DATASOURCE_PASSWORD
              value: password


          resources:
            requests:
              cpu: "200m"
              memory: "256Mi"

            limits:
              cpu: "500m"
              memory: "512Mi"
