apiVersion: apps/v1
kind: Deployment

metadata:
  name: eureka-server
  namespace: ecommerce

spec:
  replicas: 1

  selector:
    matchLabels:
      app: eureka-server

  template:
    metadata:
      labels:
        app: eureka-server

    spec:
      containers:
        - name: eureka-server
          image: asia-south1-docker.pkg.dev/project-e4b58c33-b31e-44d9-a36/ecommerce-microservices/eureka-server:5f973ac262e20fec967c67c4da6855c84eb2055d
          imagePullPolicy: IfNotPresent

          ports:
            - containerPort: 8761

          resources:
            requests:
              cpu: "100m"
              memory: "256Mi"
            limits:
              cpu: "300m"
              memory: "512Mi"
